# Generated by Django 4.1.7 on 2023-03-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название квиза')),
                ('send_results_type', models.CharField(choices=[('TG', 'В телеграмм'), ('SMS', 'По SMS'), ('TG-SMS', 'В телеграмм и по SMS')], default='TG', max_length=6, verbose_name='Тип отправки результатов')),
                ('is_send_name', models.BooleanField(default=False, verbose_name='Отправка имени')),
                ('is_send_email', models.BooleanField(default=False, verbose_name='Отправка email')),
                ('is_send_phone', models.BooleanField(default=False, verbose_name='Отправка телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Вопрос')),
                ('number', models.IntegerField(verbose_name='Порядковый номер вопроса')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'unique_together': {('quiz', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Номер ответа')),
                ('text', models.TextField(max_length=500, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'unique_together': {('question', 'num')},
            },
        ),
    ]
